- naam: Dataportaal
  omschrijving: Overzicht van beschikbare data marts, web services, triggers en toepassingen. <a href="data">Klik hier om naar het dataportaal te gaan.</a>
  uri: databronnen.json

- naam: Data marts
  omschrijving: Ontwikkeling en beheer van automatische geactualiseerde datasets op maat, voor analyse en visualisatie.

- naam: Web services
  omschrijving: Ontwikkeling en beheer van door verschillende applicaties herbruikbare back-end data services.

- naam: Triggers
  omschrijving: Ontwikkeling en beheer van automatische acties op basis van real time data.

- naam: Toepassingen
  omschrijving: Ontwikkeling en beheer online tools voor gebruik, beheer, analyse en visualisatie van data.
